<template>
  <div class="space-y-6">
    <div class="bg-white rounded-lg shadow p-4 flex flex-wrap gap-3 items-center">
      <input v-model.trim="search" placeholder="Order ID, customer, email…" class="rounded border-gray-300" />
      <select v-model="filterStatus" class="rounded border-gray-300"><option value="">All fulfilment statuses</option><option v-for="status in statuses" :key="status" :value="status">{{ label(status) }}</option></select>
      <select v-model="filterPayment" class="rounded border-gray-300"><option value="">All payments</option><option v-for="status in paymentStatuses" :key="status" :value="status">{{ label(status) }}</option></select>
      <button @click="fetchOrders" class="ml-auto px-4 py-2 border rounded hover:bg-gray-50">Refresh</button>
      <button @click="exportCSV" class="bg-green-600 text-white px-4 py-2 rounded hover:bg-green-700">Export CSV</button>
    </div>
    <div class="grid grid-cols-2 md:grid-cols-4 gap-4"><div v-for="card in summary" :key="card.label" class="bg-white rounded-lg shadow p-4"><p class="text-sm text-gray-500">{{ card.label }}</p><p class="text-2xl font-bold" :class="card.color">{{ card.value }}</p></div></div>
    <div class="bg-white rounded-lg shadow overflow-x-auto"><table class="w-full"><thead class="bg-gray-100"><tr><th class="px-4 py-3 text-left">Order</th><th class="px-4 py-3 text-left">Customer</th><th class="px-4 py-3 text-left">Total</th><th class="px-4 py-3 text-left">Payment</th><th class="px-4 py-3 text-left">Fulfilment</th><th class="px-4 py-3 text-left">Created</th><th class="px-4 py-3"></th></tr></thead><tbody><tr v-for="order in filteredOrders" :key="order._id" class="border-b"><td class="px-4 py-3 font-mono text-sm">#{{ order._id.slice(-6) }}</td><td class="px-4 py-3"><p>{{ order.customerInfo?.fullName || order.userId?.name || 'Customer' }}</p><p class="text-xs text-gray-500">{{ order.customerInfo?.phone || order.userId?.phone || '' }}</p></td><td class="px-4 py-3 font-semibold">{{ formatMoney(order.total) }}</td><td class="px-4 py-3"><span :class="pill(order.paymentStatus)">{{ label(order.paymentStatus) }}</span><p v-if="order.paymentReference" class="mt-1 text-xs text-gray-500">{{ order.paymentReference }}</p></td><td class="px-4 py-3"><span :class="pill(order.status)">{{ label(order.status) }}</span></td><td class="px-4 py-3 text-sm">{{ formatDate(order.createdAt) }}</td><td class="px-4 py-3"><button @click="openOrder(order)" class="text-primary font-semibold hover:underline">Manage</button></td></tr><tr v-if="!loading && !filteredOrders.length"><td colspan="7" class="px-4 py-10 text-center text-gray-500">No orders match these filters.</td></tr></tbody></table></div>

    <div v-if="selected" class="fixed inset-0 bg-black/40 z-50 p-4 flex items-center justify-center" @click.self="selected = null"><div class="bg-white rounded-xl max-w-2xl w-full max-h-[90vh] overflow-y-auto p-6"><div class="flex justify-between gap-4"><div><p class="text-sm text-gray-500">Order</p><h3 class="text-xl font-bold">#{{ selected._id.slice(-6) }}</h3></div><button @click="selected = null" class="text-2xl">×</button></div><div class="grid md:grid-cols-2 gap-5 mt-5"><div><h4 class="font-bold mb-2">Customer & delivery</h4><p>{{ selected.customerInfo?.fullName || selected.userId?.name }}</p><p>{{ selected.customerInfo?.email || selected.userId?.email }}</p><p>{{ selected.deliveryType }} · {{ selected.deliveryAddress }}</p><p class="text-sm text-gray-500 mt-2">{{ selected.instructions || 'No special instructions' }}</p></div><div><h4 class="font-bold mb-2">Items</h4><p v-for="item in selected.items" :key="item._id">{{ item.quantity }} × {{ item.productId?.name || 'Product' }} — {{ formatMoney(item.price * item.quantity) }}</p><p class="font-bold mt-2">Total: {{ formatMoney(selected.total) }}</p></div></div><div class="border-t mt-6 pt-5 grid sm:grid-cols-2 gap-4"><label class="text-sm font-semibold">Fulfilment<select v-model="edit.status" class="mt-1 w-full rounded border-gray-300"><option v-for="status in statuses" :key="status" :value="status">{{ label(status) }}</option></select></label><label class="text-sm font-semibold">Payment<select v-model="edit.paymentStatus" class="mt-1 w-full rounded border-gray-300"><option v-for="status in paymentStatuses" :key="status" :value="status">{{ label(status) }}</option></select></label><label class="text-sm font-semibold sm:col-span-2">Payment reference / receipt number<input v-model.trim="edit.paymentReference" class="mt-1 w-full rounded border-gray-300" /></label><label class="text-sm font-semibold sm:col-span-2">Internal note (included in audit trail)<textarea v-model.trim="edit.note" rows="2" class="mt-1 w-full rounded border-gray-300"></textarea></label></div><button @click="saveOrder" :disabled="saving" class="btn-primary mt-5">{{ saving ? 'Saving…' : 'Save operational update' }}</button><div class="border-t mt-6 pt-4"><h4 class="font-bold mb-3">Audit history</h4><p v-if="!selected.statusHistory?.length" class="text-sm text-gray-500">No recorded updates.</p><ol v-else class="space-y-2 text-sm"><li v-for="entry in selected.statusHistory.slice().reverse()" :key="entry._id" class="bg-gray-50 p-3 rounded"><span class="font-semibold">{{ label(entry.status) }} · {{ label(entry.paymentStatus) }}</span><span class="text-gray-500"> — {{ formatDate(entry.changedAt) }}</span><p v-if="entry.note" class="mt-1">{{ entry.note }}</p></li></ol></div></div></div>
  </div>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue'
import apiClient from '@/utils/api'
const orders = ref([]); const loading = ref(false); const search = ref(''); const filterStatus = ref(''); const filterPayment = ref(''); const selected = ref(null); const saving = ref(false)
const statuses = ['pending', 'confirmed', 'preparing', 'out_for_delivery', 'delivered', 'cancelled']; const paymentStatuses = ['pending', 'paid', 'failed', 'refunded']
const label = value => (value || 'pending').replaceAll('_', ' ').replace(/\b\w/g, char => char.toUpperCase())
const formatDate = value => new Date(value).toLocaleString(); const formatMoney = value => `${Number(value || 0).toLocaleString()} RWF`
const filteredOrders = computed(() => orders.value.filter(order => { const term = search.value.toLowerCase(); return (!filterStatus.value || order.status === filterStatus.value) && (!filterPayment.value || order.paymentStatus === filterPayment.value) && (!term || [order._id, order.customerInfo?.fullName, order.customerInfo?.email, order.userId?.name, order.userId?.email].filter(Boolean).join(' ').toLowerCase().includes(term)) }))
const summary = computed(() => [{ label: 'Pending orders', value: orders.value.filter(o => o.status === 'pending').length, color: 'text-amber-600' }, { label: 'Awaiting payment', value: orders.value.filter(o => o.paymentStatus === 'pending').length, color: 'text-red-600' }, { label: 'Preparing / delivery', value: orders.value.filter(o => ['preparing', 'out_for_delivery'].includes(o.status)).length, color: 'text-blue-600' }, { label: 'Completed', value: orders.value.filter(o => o.status === 'delivered').length, color: 'text-green-600' }])
const edit = ref({})
async function fetchOrders() { loading.value = true; try { orders.value = (await apiClient.get('/admin/orders')).data } finally { loading.value = false } }
async function openOrder(order) { selected.value = (await apiClient.get(`/admin/orders/${order._id}`)).data; edit.value = { status: selected.value.status, paymentStatus: selected.value.paymentStatus || 'pending', paymentReference: selected.value.paymentReference || '', note: '' } }
async function saveOrder() { saving.value = true; try { selected.value = (await apiClient.patch(`/admin/orders/${selected.value._id}/status`, edit.value)).data; await openOrder(selected.value); await fetchOrders() } finally { saving.value = false } }
async function exportCSV() { const response = await apiClient.get('/admin/orders/export/csv', { responseType: 'blob' }); const url = URL.createObjectURL(response.data); const link = document.createElement('a'); link.href = url; link.download = 'orders.csv'; link.click(); URL.revokeObjectURL(url) }
onMounted(fetchOrders)
</script>
