<template>
  <div class="space-y-6">
    <section class="rounded-2xl bg-gradient-to-r from-stone-950 to-amber-900 text-white p-7 shadow-lg"><div class="flex flex-col md:flex-row justify-between gap-5 md:items-center"><div><p class="text-amber-200 text-sm font-semibold uppercase tracking-wider">Admin operations centre</p><h3 class="text-3xl font-bold mt-1">Keep service moving</h3><p class="text-stone-200 mt-2">Review orders, verify payments, and solve issues before they reach customers.</p></div><button @click="$emit('navigate', 'orders')" class="bg-white text-dark px-5 py-3 rounded-lg font-bold">Open order desk</button></div></section>
    <section class="grid grid-cols-2 xl:grid-cols-4 gap-4"><button v-for="card in cards" :key="card.label" @click="$emit('navigate', card.section)" :class="['text-left p-5 rounded-xl border hover:shadow transition', card.style]"><p class="text-sm">{{ card.label }}</p><p class="text-3xl font-bold mt-1">{{ card.value }}</p><p class="text-xs mt-2 opacity-80">{{ card.hint }}</p></button></section>
    <section class="grid lg:grid-cols-3 gap-6"><div class="lg:col-span-2 bg-white rounded-xl border shadow-sm p-6"><div class="flex justify-between items-center mb-4"><div><h3 class="text-xl font-bold">Latest orders</h3><p class="text-sm text-gray-500">Work queue for the bakery and delivery team</p></div><button @click="$emit('navigate', 'orders')" class="text-primary font-semibold text-sm">View all →</button></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="border-b text-left text-gray-500"><tr><th class="pb-3">Order</th><th class="pb-3">Customer</th><th class="pb-3">Payment</th><th class="pb-3">Service</th><th class="pb-3 text-right">Total</th></tr></thead><tbody><tr v-for="order in recentOrders" :key="order._id" class="border-b last:border-0"><td class="py-3 font-mono">#{{ order._id.slice(-6) }}</td><td class="py-3"><p class="font-medium">{{ order.customerInfo?.fullName || order.userId?.name || 'Customer' }}</p><p class="text-xs text-gray-500">{{ date(order.createdAt) }}</p></td><td class="py-3"><span :class="pill(order.paymentStatus)">{{ label(order.paymentStatus) }}</span></td><td class="py-3"><span :class="pill(order.status)">{{ label(order.status) }}</span></td><td class="py-3 text-right font-semibold">{{ money(order.total) }}</td></tr><tr v-if="!recentOrders.length"><td colspan="5" class="py-8 text-center text-gray-500">No orders yet.</td></tr></tbody></table></div></div><div class="space-y-6"><div class="bg-white rounded-xl border shadow-sm p-6"><p class="text-sm text-gray-500">Verified paid revenue</p><p class="text-3xl font-bold text-green-700 mt-1">{{ money(stats.totals.paidRevenue) }}</p><p class="text-xs text-gray-500 mt-2">Only orders marked as paid</p><div class="grid grid-cols-2 gap-3 border-t mt-5 pt-4 text-sm"><div><p class="text-gray-500">Today</p><b>{{ money(stats.today.revenue) }}</b></div><div><p class="text-gray-500">This month</p><b>{{ money(stats.month.revenue) }}</b></div></div></div><div class="bg-white rounded-xl border shadow-sm p-6"><div class="flex justify-between"><h3 class="font-bold">Inventory alerts</h3><button @click="$emit('navigate', 'products')" class="text-primary text-sm">Manage</button></div><div v-if="lowStock.length" class="mt-3 space-y-3"><div v-for="product in lowStock.slice(0, 4)" :key="product._id" class="flex justify-between text-sm"><span>{{ product.name }}</span><b class="text-red-600">{{ product.stock }} left</b></div></div><p v-else class="text-sm text-green-700 mt-3">Stock levels look healthy.</p></div></div></section>
  </div>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue'
import apiClient from '@/utils/api'
defineEmits(['navigate'])
const stats = ref({ today: { revenue: 0 }, month: { revenue: 0 }, totals: { pendingOrders: 0, unpaidOrders: 0, activeOrders: 0, paidRevenue: 0 } }); const recentOrders = ref([]); const lowStock = ref([])
const cards = computed(() => [{ label: 'New orders', value: stats.value.totals.pendingOrders, hint: 'Need confirmation', section: 'orders', style: 'bg-amber-50 border-amber-200 text-amber-900' }, { label: 'Awaiting payment', value: stats.value.totals.unpaidOrders, hint: 'Verify receipt or reference', section: 'orders', style: 'bg-red-50 border-red-200 text-red-900' }, { label: 'In service', value: stats.value.totals.activeOrders, hint: 'Preparing or delivering', section: 'orders', style: 'bg-blue-50 border-blue-200 text-blue-900' }, { label: 'Low stock alerts', value: lowStock.value.length, hint: 'Review inventory', section: 'products', style: 'bg-purple-50 border-purple-200 text-purple-900' }])
const label = value => (value || 'pending').replaceAll('_', ' ').replace(/\b\w/g, char => char.toUpperCase()); const money = value => `${Number(value || 0).toLocaleString()} RWF`; const date = value => new Date(value).toLocaleString(); const pill = value => ({ paid: 'bg-green-100 text-green-800', pending: 'bg-amber-100 text-amber-800', failed: 'bg-red-100 text-red-800', refunded: 'bg-purple-100 text-purple-800', confirmed: 'bg-blue-100 text-blue-800', preparing: 'bg-yellow-100 text-yellow-800', out_for_delivery: 'bg-indigo-100 text-indigo-800', delivered: 'bg-green-100 text-green-800', cancelled: 'bg-gray-100 text-gray-700' }[value] || 'bg-gray-100 text-gray-700') + ' px-2 py-1 rounded-full text-xs font-medium'
onMounted(async () => { const [a, b, c] = await Promise.all([apiClient.get('/admin/stats'), apiClient.get('/admin/recent-orders'), apiClient.get('/admin/low-stock')]); stats.value = a.data; recentOrders.value = b.data; lowStock.value = c.data })
</script>
